---
- name: Install tmux #Terminal Multiplexer
  pacman: name=tmux state=present
  become: yes

- name: Configure .tmux.conf
  copy: src=.tmux.conf dest="/home/{{ user_name }}/.tmux.conf owner={{ user_name}} group=users
  become: yes
  become_user: {{ user_name }}
  
