- name: yew
  hosts: localhost

  roles:
    - role: user
    - role: utils
    - role: editor
    - role: gui
    - role: web
    - role: media

  vars_prompt:
    - name: user_password
      prompt: "Enter user password"
      private: yes
      encrypt: "md5_crypt" # Requires python-passlib installed on system.
      confirm: yes
      set_salt: 7
    - name: ssh_pass
      prompt: "Enter ssh_key password"
      private: yes
      confirm: yes
