- name: yew
  hosts: localhost

  roles:
    - role: user

  vars_prompt:
    - name: user_name
      prompt: "Enter user name:"
      private: no

    - name: user_password
      prompt: "Enter user password:"
      private: yes
      encrypt: "md5_crypt" # Requires python-passlib installed on system.
      confirm: yes
      set_salt: 7
 
    - name: git_name
      prompt: "Enter git username:"
      private: no

    - name: git_email
      prompt: "Enter git email"
      private: no
