- name: yew
  hosts: localhost

  roles:
    - role: user
    - role: util
    - role: editor
    - role: gui

  vars_prompt:
    - name: user_password
      prompt: "Enter user password:"
      private: yes
      encrypt: "md5_crypt" # Requires python-passlib installed on system.
      confirm: yes
      set_salt: 7
