---
- name: Create user group
  group: name={{ user_name }} state=present

- name: Create user and add to group
  user: name={{ user_name }} group={{ user_name }} password={{ user_password }} update_password=on_create

