---
#
# Install 'st' terminal emulator and a few scripts to improve startup.
#
- name: Create st dir.
  file: path="/home/{{ user_name }}/.gui/st" owner={{ user_name }} group={{ user_name }} state=directory
  become: yes
  become_user: "{{ user_name }}"
  
- name: Get my custom st source
  git: repo=https://github.com/gavinsunde/st.git dest="/home/{{ user_name }}/.gui/st"
  args:
    version: grs/0.7
  become: yes
  become_user: "{{ user_name }}"

- name: Compile st
  shell: make clean install >> compile.log
  args:
    chdir: "/home/{{ user_name }}/.gui/st/"
    creates: compile.log
  become: yes
  become_method: sudo

# Attaches to or starts 'st' with a tmux session named '0'.
- name: Copy st0 startup script
  copy: src=st0 dest=/usr/local/bin/st0
  become: yes

# Attaches to or starts 'st' with a tmux session named '1'.
- name: Copy st1 startup script
  copy: src=st1 dest=/usr/local/bin/st1
  become: yes

# Starts 'st' with a ssh session to pine
- name: Copy pine startup script
  copy: src=pine dest=/usr/local/bin/pine
  become: yes

# Attaches to or starts 'st' with a tmux session named 'env' to run music/irc/ect.
- name: Copy env startup script
  copy: src=env dest=/usr/local/bin/env
  become: yes
