---
- name: install feh
  pacman: name=feh
  become: yes

- name: Background
  copy: src=.wallpapers/ dest="/home/{{ user_name}}/.wallpapers/" owner={{ user_name }} group={{ user_name }}
  become: yes

