---
- name: install feh
  pacman: name=feh
  become: yes

- name: configure wallpaper script
  template: src=fehbg dest=/home/{{ user_name }}/.fehbg owner={{ user_name }} group=users
  become: yes
  become_user: "{{ user_name }}"

